language: python
python:
  - "2.7"
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=pypy
install:
  - "pip install tox --download-cache $HOME/.pip-cache"
  - "pip install coveralls --download-cache $HOME/.pip-cache"
  - git clone --quiet --depth=100 "https://github.com/nanomsg/nanomsg.git" ~/builds/nanomsg
      && pushd ~/builds/nanomsg
      && ./autogen.sh
      && ./configure
      && make 
      && sudo make install
      && popd;
script: LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib tox -e $TOX_ENV
after_success:
  - coveralls
cache:
  directories:
    - .tox
    - $HOME/.pip-cache/
